export type ExerciseType =
  | "recognition"
  | "production"
  | "case_ending"
  | "odd_one_out"
  | "conversation"
  | "fix_the_mistake"
  | "family_vocab";

export interface CardSeed {
  id: string;
  topic: string;
  grammarPoint: string;
  preferredType?: ExerciseType;
}

export interface Skill {
  id: string;
  name: string;
  finnishName: string;
  track: "A" | "B";
  order: number;
  unlockAfter: string[];
  isLeahSkill: boolean;
  description: string;
  seeds: CardSeed[];
}

export const SKILLS: Skill[] = [
  {
    id: "s1",
    name: "Greetings & Farewells",
    finnishName: "Tervehdykset",
    track: "A",
    order: 1,
    unlockAfter: [],
    isLeahSkill: false,
    description: "Hei, moi, terve and how to greet people throughout the day",
    seeds: [
      { id: "s1-0", topic: "hei and moi as casual greetings", grammarPoint: "informal greetings" },
      { id: "s1-1", topic: "terve as a slightly more formal casual greeting", grammarPoint: "informal greetings" },
      { id: "s1-2", topic: "hyvää huomenta — good morning", grammarPoint: "time-of-day greetings" },
      { id: "s1-3", topic: "hyvää päivää — good afternoon/day", grammarPoint: "time-of-day greetings" },
      { id: "s1-4", topic: "hyvää iltaa — good evening", grammarPoint: "time-of-day greetings" },
      { id: "s1-5", topic: "hyvää yötä — good night", grammarPoint: "time-of-day greetings" },
      { id: "s1-6", topic: "näkemiin — formal goodbye", grammarPoint: "farewells formal" },
      { id: "s1-7", topic: "heippa and moi moi — casual goodbye", grammarPoint: "farewells informal" },
      { id: "s1-8", topic: "nähdään — see you (lit. we'll see each other)", grammarPoint: "passive farewell" },
      { id: "s1-9", topic: "hauska tutustua — nice to meet you", grammarPoint: "introductions" },
      { id: "s1-10", topic: "hauska tavata — nice to meet you (when meeting)", grammarPoint: "introductions" },
      { id: "s1-11", topic: "responding to hyvää huomenta with hyvää huomenta", grammarPoint: "greeting responses" },
      { id: "s1-12", topic: "mitä kuuluu? — how are you?", grammarPoint: "asking how someone is" },
      { id: "s1-13", topic: "hyvää kuuluu, kiitos — I'm good, thanks", grammarPoint: "responding to how are you" },
      { id: "s1-14", topic: "kiitos — thank you, ole hyvä — you're welcome", grammarPoint: "politeness" },
      { id: "s1-15", topic: "anteeksi — excuse me / sorry", grammarPoint: "politeness" },
      { id: "s1-16", topic: "ole hyvä — you're welcome / here you go", grammarPoint: "politeness" },
      { id: "s1-17", topic: "tervetuloa — welcome", grammarPoint: "hospitality greetings" },
      { id: "s1-18", topic: "differences between hei/moi/terve in usage context", grammarPoint: "register differences" },
      { id: "s1-19", topic: "colloquial: moro as a regional greeting in Tampere area", grammarPoint: "regional variants" },
      { id: "s1-20", topic: "responding when someone greets you first", grammarPoint: "conversation flow" },
      { id: "s1-21", topic: "greeting someone you haven't seen in a while", grammarPoint: "reacquainting" },
      { id: "s1-22", topic: "formal vs informal contexts: when to use hei vs hyvää päivää", grammarPoint: "register" },
      { id: "s1-23", topic: "paljon onnea — congratulations / happy birthday", grammarPoint: "special greetings" },
      { id: "s1-24", topic: "hyvää viikonloppua — have a good weekend", grammarPoint: "weekend greetings" },
      { id: "s1-25", topic: "näkemiin vs heippa — when each is appropriate", grammarPoint: "farewell register" },
      { id: "s1-26", topic: "conversation: meeting Oskari's family member at the door", grammarPoint: "situational greetings" },
      { id: "s1-27", topic: "hai vs hei — common spelling confusion", grammarPoint: "spelling" },
      { id: "s1-28", topic: "greeting and farewell mini-dialogue practice", grammarPoint: "conversation" },
      { id: "s1-29", topic: "tervetuloa Suomeen — welcome to Finland", grammarPoint: "hospitality" },
    ],
  },
  {
    id: "s2",
    name: "About Me",
    finnishName: "Minusta",
    track: "A",
    order: 2,
    unlockAfter: ["s1"],
    isLeahSkill: true,
    description: "Leah's real life in Finnish — where she lives, what she does, her cats",
    seeds: [
      { id: "s2-0", topic: "Asun Culver Cityssä, Los Angelesissa — I live in Culver City, LA", grammarPoint: "inessive case for cities", preferredType: "production" },
      { id: "s2-1", topic: "Asun Oskarin kanssa — I live with Oskari", grammarPoint: "kanssa postposition", preferredType: "production" },
      { id: "s2-2", topic: "Meillä on kaksi kissaa — We have two cats", grammarPoint: "meillä on construction + partitive", preferredType: "production" },
      { id: "s2-3", topic: "Kissojen nimet ovat Kiki ja Karl — The cats' names are Kiki and Karl", grammarPoint: "genitive plural + olla", preferredType: "production" },
      { id: "s2-4", topic: "Olen data-analyytikko — I am a data analyst", grammarPoint: "olen + profession (no article)", preferredType: "production" },
      { id: "s2-5", topic: "Työskentelen uusiutuvan energian alalla — I work in the renewable energy sector", grammarPoint: "adessive case alalla", preferredType: "production" },
      { id: "s2-6", topic: "Opiskelin matematiikkaa yliopistossa — I studied mathematics at university", grammarPoint: "partitive object + inessive", preferredType: "production" },
      { id: "s2-7", topic: "Puhun vähän suomea — I speak a little Finnish", grammarPoint: "partitive object after puhun", preferredType: "production" },
      { id: "s2-8", topic: "Opiskelen suomea — I am studying Finnish", grammarPoint: "partitive object", preferredType: "production" },
      { id: "s2-9", topic: "Yritän parhaani — I'm doing my best", grammarPoint: "idiomatic expression", preferredType: "production" },
      { id: "s2-10", topic: "Olen amerikkalainen — I am American", grammarPoint: "nationality adjectives", preferredType: "production" },
      { id: "s2-11", topic: "Mistä olet kotoisin? — Where are you from? responding with Los Angelesista", grammarPoint: "elative case for origin" },
      { id: "s2-12", topic: "Mikä sinun nimesi on? / Mikä on nimesi? — What is your name?", grammarPoint: "name question" },
      { id: "s2-13", topic: "Minun nimeni on Leah — My name is Leah", grammarPoint: "possessive suffix or minun", preferredType: "production" },
      { id: "s2-14", topic: "Kuinka vanha olet? / Olen X-vuotias — How old are you / I am X years old", grammarPoint: "age expression" },
      { id: "s2-15", topic: "Asutko Suomessa? / En, asun Yhdysvalloissa — Do you live in Finland? No, I live in the US", grammarPoint: "yes/no question + negation" },
      { id: "s2-16", topic: "Millainen työ sinulla on? — What kind of work do you have?", grammarPoint: "millainen question" },
      { id: "s2-17", topic: "Onko sinulla lapsia? Ei ole, mutta meillä on kaksi kissaa — Do you have children? No, but we have two cats", grammarPoint: "onko + negation" },
      { id: "s2-18", topic: "Kauanko olet opiskellut suomea? — How long have you studied Finnish?", grammarPoint: "kauanko + perfect tense" },
      { id: "s2-19", topic: "Tykkään Suomesta — I like Finland", grammarPoint: "elative with tykkään" },
      { id: "s2-20", topic: "Olen iloinen, että olen täällä — I am happy to be here", grammarPoint: "että clause" },
      { id: "s2-21", topic: "production: full self-introduction combining name, city, job", grammarPoint: "multi-sentence production", preferredType: "production" },
      { id: "s2-22", topic: "production: talking about the cats Kiki and Karl", grammarPoint: "pet vocabulary", preferredType: "production" },
      { id: "s2-23", topic: "production: explaining what renewable energy is in simple Finnish", grammarPoint: "workplace vocabulary" },
      { id: "s2-24", topic: "Olen Oskarin tyttöystävä — I am Oskari's girlfriend", grammarPoint: "genitive possession" },
      { id: "s2-25", topic: "Asumme yhdessä — We live together", grammarPoint: "first person plural" },
      { id: "s2-26", topic: "Tulen Los Angelesista — I come from Los Angeles", grammarPoint: "elative case" },
      { id: "s2-27", topic: "fix the mistake: wrong case after asun", grammarPoint: "inessive case", preferredType: "fix_the_mistake" },
      { id: "s2-28", topic: "fix the mistake: missing partitive on suomea", grammarPoint: "partitive object", preferredType: "fix_the_mistake" },
      { id: "s2-29", topic: "conversation: Oskari's relative asks where you're from and what you do", grammarPoint: "situational dialogue", preferredType: "conversation" },
    ],
  },
  {
    id: "s3",
    name: "Hobbies & Abilities",
    finnishName: "Harrastukset",
    track: "A",
    order: 3,
    unlockAfter: ["s2"],
    isLeahSkill: true,
    description: "tykkään + inf, osaan + inf, and Leah's actual hobbies",
    seeds: [
      { id: "s3-0", topic: "tykkään juosta — I like to run", grammarPoint: "tykkään + infinitive", preferredType: "production" },
      { id: "s3-1", topic: "tykkään neuloa — I like to knit", grammarPoint: "tykkään + infinitive", preferredType: "production" },
      { id: "s3-2", topic: "tykkään lukea — I like to read", grammarPoint: "tykkään + infinitive", preferredType: "production" },
      { id: "s3-3", topic: "tykkään syödä pizzaa — I like to eat pizza", grammarPoint: "tykkään + infinitive + partitive object", preferredType: "production" },
      { id: "s3-4", topic: "tykkään tehdä ruokaa — I like to cook (make food)", grammarPoint: "tykkään + infinitive", preferredType: "production" },
      { id: "s3-5", topic: "tykkään järjestää — I like to organize", grammarPoint: "tykkään + infinitive", preferredType: "production" },
      { id: "s3-6", topic: "osaan neuloa — I know how to knit", grammarPoint: "osaan + infinitive" },
      { id: "s3-7", topic: "osaan tehdä ruokaa — I know how to cook", grammarPoint: "osaan + infinitive", preferredType: "production" },
      { id: "s3-8", topic: "juoksen joka päivä — I run every day", grammarPoint: "simple present tense" },
      { id: "s3-9", topic: "luen kirjoja — I read books (partitive plural)", grammarPoint: "partitive plural object" },
      { id: "s3-10", topic: "tykkään + inf vs tykkään + elative (tykkään juoksemisesta)", grammarPoint: "two constructions for liking" },
      { id: "s3-11", topic: "Tykkäätkö sinä juosta? — Do you like to run?", grammarPoint: "question with tykkäät" },
      { id: "s3-12", topic: "En tykkää uida — I don't like to swim (negation of tykkään)", grammarPoint: "negation of tykkään" },
      { id: "s3-13", topic: "helping grandparents: auttaa siivoamaan — help with cleaning", grammarPoint: "auttaa + infinitive" },
      { id: "s3-14", topic: "helping grandparents: kantaa kasseja — carry bags", grammarPoint: "physical help vocabulary" },
      { id: "s3-15", topic: "helping grandparents: laittaa ruokaa — prepare food", grammarPoint: "domestic help vocabulary" },
      { id: "s3-16", topic: "Voinko auttaa? — Can I help?", grammarPoint: "offering help politely", preferredType: "production" },
      { id: "s3-17", topic: "Haluatko apua? — Do you want help?", grammarPoint: "asking if help is wanted" },
      { id: "s3-18", topic: "Mitä harrastuksia sinulla on? — What hobbies do you have?", grammarPoint: "harrastus vocabulary" },
      { id: "s3-19", topic: "Minulla on monta harrastusta — I have many hobbies", grammarPoint: "monta + partitive" },
      { id: "s3-20", topic: "osaan vs tykkään — ability vs preference", grammarPoint: "modal distinction" },
      { id: "s3-21", topic: "production: full sentence Tykkään juosta, neuloa ja lukea", grammarPoint: "list with ja", preferredType: "production" },
      { id: "s3-22", topic: "production: ja syödä Oskarin ruokaa — and eating Oskari's food", grammarPoint: "genitive possession + infinitive", preferredType: "production" },
      { id: "s3-23", topic: "Oskari tekee hyvää ruokaa — Oskari makes good food", grammarPoint: "hyvää partitive adjective" },
      { id: "s3-24", topic: "odd one out: juosta / neuloa / tyttöystävä / lukea", grammarPoint: "verb vs noun", preferredType: "odd_one_out" },
      { id: "s3-25", topic: "Mikä on lempiharrastuksesi? — What is your favorite hobby?", grammarPoint: "lempi- compound + possessive" },
      { id: "s3-26", topic: "Harrastatko liikuntaa? — Do you exercise / do sports?", grammarPoint: "harrastaa verb" },
      { id: "s3-27", topic: "fix the mistake: wrong verb form after tykkään", grammarPoint: "infinitive after tykkään", preferredType: "fix_the_mistake" },
      { id: "s3-28", topic: "conversation: telling family member about your hobbies", grammarPoint: "situational dialogue", preferredType: "conversation" },
      { id: "s3-29", topic: "Neulon villasukkia isoäidille — I'm knitting wool socks for grandmother", grammarPoint: "allative case for recipient" },
    ],
  },
  {
    id: "s4",
    name: "Family",
    finnishName: "Perhe",
    track: "A",
    order: 4,
    unlockAfter: ["s1"],
    isLeahSkill: false,
    description: "Finnish family vocabulary and how to talk about relatives",
    seeds: [
      { id: "s4-0", topic: "perhe — family", grammarPoint: "basic vocabulary", preferredType: "family_vocab" },
      { id: "s4-1", topic: "äiti — mother, isä — father", grammarPoint: "parent terms", preferredType: "family_vocab" },
      { id: "s4-2", topic: "isoäiti — grandmother, isoisä — grandfather", grammarPoint: "grandparent terms", preferredType: "family_vocab" },
      { id: "s4-3", topic: "sisko — sister, veli — brother", grammarPoint: "sibling terms", preferredType: "family_vocab" },
      { id: "s4-4", topic: "täti — aunt, setä — uncle", grammarPoint: "aunt and uncle terms", preferredType: "family_vocab" },
      { id: "s4-5", topic: "serkku — cousin (gender neutral)", grammarPoint: "cousin term", preferredType: "family_vocab" },
      { id: "s4-6", topic: "anoppi — mother-in-law, appi — father-in-law", grammarPoint: "in-law terms (partner's parents)", preferredType: "family_vocab" },
      { id: "s4-7", topic: "miniä — daughter-in-law, vävy — son-in-law", grammarPoint: "in-law terms" },
      { id: "s4-8", topic: "käly — sister-in-law", grammarPoint: "in-law terms", preferredType: "family_vocab" },
      { id: "s4-9", topic: "lapsi — child, lapset — children (plural)", grammarPoint: "child + plural" },
      { id: "s4-10", topic: "poika — son/boy, tyttö — daughter/girl", grammarPoint: "children terms" },
      { id: "s4-11", topic: "Minulla on iso perhe / pieni perhe — I have a big/small family", grammarPoint: "minulla on + adjective" },
      { id: "s4-12", topic: "Oskarin äiti on nimeltään X — Oskari's mother is named X", grammarPoint: "nimeltään expression" },
      { id: "s4-13", topic: "Onko sinulla sisaruksia? — Do you have siblings?", grammarPoint: "sisarukset plural" },
      { id: "s4-14", topic: "Minulla on yksi sisko — I have one sister", grammarPoint: "nominative after yksi" },
      { id: "s4-15", topic: "Hänellä on kaksi lasta — He/she has two children", grammarPoint: "hänellä on + partitive" },
      { id: "s4-16", topic: "Kuinka monta lasta heillä on? — How many children do they have?", grammarPoint: "kuinka monta + partitive" },
      { id: "s4-17", topic: "Onko isoisä kotona? — Is grandfather at home?", grammarPoint: "onko + location" },
      { id: "s4-18", topic: "complimenting family: Teillä on ihana perhe — You have a wonderful family", grammarPoint: "compliment expression", preferredType: "production" },
      { id: "s4-19", topic: "Perheenne on hyvin ystävällinen — Your family is very friendly", grammarPoint: "possessive suffix -nne" },
      { id: "s4-20", topic: "odd one out: äiti / isä / serkku / talo / isoäiti", grammarPoint: "family vs non-family", preferredType: "odd_one_out" },
      { id: "s4-21", topic: "vanhemmat — parents (plural)", grammarPoint: "vanhempi plural" },
      { id: "s4-22", topic: "sukulainen — relative, sukulaiset — relatives", grammarPoint: "extended family" },
      { id: "s4-23", topic: "asking about Oskari's family members by name", grammarPoint: "conversation practice" },
      { id: "s4-24", topic: "Isoisä on eläkkeellä — Grandfather is retired", grammarPoint: "eläkkeellä expression" },
      { id: "s4-25", topic: "Isoäiti asuu maalla — Grandmother lives in the countryside", grammarPoint: "adessive maalla" },
      { id: "s4-26", topic: "fix the mistake: wrong possessive for family member", grammarPoint: "genitive possession", preferredType: "fix_the_mistake" },
      { id: "s4-27", topic: "Miten isoisällä menee? — How is grandfather doing?", grammarPoint: "adessive + menee idiom" },
      { id: "s4-28", topic: "conversation: being introduced to Oskari's grandmother", grammarPoint: "introduction dialogue", preferredType: "conversation" },
      { id: "s4-29", topic: "Hän on Oskarin mummo — She is Oskari's grandma (colloquial mummo vs isoäiti)", grammarPoint: "colloquial family terms" },
    ],
  },
  {
    id: "s5",
    name: "Food & Eating",
    finnishName: "Ruoka",
    track: "A",
    order: 5,
    unlockAfter: ["s1"],
    isLeahSkill: false,
    description: "Ordering, expressing preferences, complimenting Finnish food",
    seeds: [
      { id: "s5-0", topic: "Tämä on herkullista — This is delicious", grammarPoint: "partitive predicate adjective", preferredType: "production" },
      { id: "s5-1", topic: "Saisinko lisää? — Could I have more?", grammarPoint: "conditional saisin + lisää", preferredType: "production" },
      { id: "s5-2", topic: "Olen allerginen pähkinöille — I am allergic to nuts", grammarPoint: "allergic + allative" },
      { id: "s5-3", topic: "En syö naudanlihaa — I don't eat beef", grammarPoint: "negation + partitive object" },
      { id: "s5-4", topic: "Saisinko vettä? — Could I have some water?", grammarPoint: "conditional polite request + partitive" },
      { id: "s5-5", topic: "Haluatko lisää ruokaa? — Do you want more food?", grammarPoint: "haluatko question" },
      { id: "s5-6", topic: "Kiitos, se oli todella hyvää — Thank you, that was really good", grammarPoint: "compliment after meal", preferredType: "production" },
      { id: "s5-7", topic: "tykkään pizzasta — I like pizza (elative)", grammarPoint: "elative after tykkään" },
      { id: "s5-8", topic: "tykkään meksikolaisesta ruoasta — I like Mexican food", grammarPoint: "elative + adjective agreement" },
      { id: "s5-9", topic: "hedelmät — fruits, vihannekset — vegetables", grammarPoint: "food category vocabulary" },
      { id: "s5-10", topic: "suklaa — chocolate, kahvi — coffee, tee — tea", grammarPoint: "common food items" },
      { id: "s5-11", topic: "Finnish foods: silli (herring), ruis (rye), karjalanpiirakka, mämmi", grammarPoint: "Finnish food culture" },
      { id: "s5-12", topic: "Onko teillä kasvisruokaa? — Do you have vegetarian food?", grammarPoint: "onko + partitive" },
      { id: "s5-13", topic: "Ruoka oli maistuvaa — The food was tasty", grammarPoint: "maistua adjective" },
      { id: "s5-14", topic: "Saako täällä syödä? — Is eating allowed here?", grammarPoint: "saako + infinitive" },
      { id: "s5-15", topic: "Mitä haluaisit syödä? — What would you like to eat?", grammarPoint: "haluaisit conditional" },
      { id: "s5-16", topic: "odd one out: kahvi / tee / pöytä / suklaa", grammarPoint: "drinks and chocolate vs furniture", preferredType: "odd_one_out" },
      { id: "s5-17", topic: "Laittaa ruokaa — to cook/prepare food", grammarPoint: "laittaa ruokaa expression" },
      { id: "s5-18", topic: "Kuka laittoi ruoan? — Who cooked the food?", grammarPoint: "past tense question" },
      { id: "s5-19", topic: "complimenting the cook: Olet mestarikokit — You are a master chef", grammarPoint: "complimenting abilities" },
      { id: "s5-20", topic: "Syön kasviksia — I eat vegetables (partitive ongoing)", grammarPoint: "partitive habitual action" },
      { id: "s5-21", topic: "En juo alkoholia — I don't drink alcohol", grammarPoint: "negation + partitive" },
      { id: "s5-22", topic: "Juon kahvia aamiaisella — I drink coffee at breakfast", grammarPoint: "adessive time expression" },
      { id: "s5-23", topic: "Onko ruoka valmis? — Is the food ready?", grammarPoint: "valmis adjective" },
      { id: "s5-24", topic: "Ruokapöytä — dining table, kitchen vocabulary", grammarPoint: "kitchen and dining vocabulary" },
      { id: "s5-25", topic: "cultural note: taking seconds is polite in Finnish homes, Saisinko lisää?", grammarPoint: "Finnish food culture etiquette" },
      { id: "s5-26", topic: "fix the mistake: wrong case on food object after syödä", grammarPoint: "partitive object", preferredType: "fix_the_mistake" },
      { id: "s5-27", topic: "conversation: at dinner with Oskari's family, complimenting isoäiti's food", grammarPoint: "dinner conversation", preferredType: "conversation" },
      { id: "s5-28", topic: "Miten ruoka maistuu? — How does the food taste?", grammarPoint: "maistua verb" },
      { id: "s5-29", topic: "Hyvää ruokahalua! — Enjoy your meal! (lit. good appetite)", grammarPoint: "meal blessing" },
    ],
  },
  {
    id: "s6",
    name: "Weather & Seasons",
    finnishName: "Sää ja vuodenajat",
    track: "A",
    order: 6,
    unlockAfter: ["s1"],
    isLeahSkill: false,
    description: "Weather talk — Finland's #1 small talk topic",
    seeds: [
      { id: "s6-0", topic: "Sataa lunta — It is snowing (lit. it rains snow)", grammarPoint: "sataa + partitive noun" },
      { id: "s6-1", topic: "Sataa vettä — It is raining", grammarPoint: "sataa + partitive noun" },
      { id: "s6-2", topic: "Aurinko paistaa — The sun is shining", grammarPoint: "subject + verb" },
      { id: "s6-3", topic: "On kylmä — It is cold", grammarPoint: "impersonal on + adjective" },
      { id: "s6-4", topic: "On lämmin — It is warm", grammarPoint: "impersonal on + adjective" },
      { id: "s6-5", topic: "On kuuma — It is hot", grammarPoint: "impersonal on + adjective" },
      { id: "s6-6", topic: "Millainen sää on tänään? — What is the weather like today?", grammarPoint: "millainen weather question" },
      { id: "s6-7", topic: "Sää on upea — The weather is wonderful", grammarPoint: "sää + on + adjective" },
      { id: "s6-8", topic: "Talvi — winter, kevät — spring, kesä — summer, syksy — autumn", grammarPoint: "seasons vocabulary" },
      { id: "s6-9", topic: "Suomen talvi on ankara — Finnish winter is harsh", grammarPoint: "seasons adjective" },
      { id: "s6-10", topic: "Heinäkuussa on lämmin — In July it is warm", grammarPoint: "inessive for months" },
      { id: "s6-11", topic: "Onko Suomessa lunta nyt? — Is there snow in Finland now?", grammarPoint: "onko + inessive" },
      { id: "s6-12", topic: "Pilvet — clouds, tuulee — it is windy", grammarPoint: "weather phenomena" },
      { id: "s6-13", topic: "Lämpötila on miinus kymmenen — The temperature is minus ten", grammarPoint: "temperature expression" },
      { id: "s6-14", topic: "Plussaa / miinusta — positive / negative degrees", grammarPoint: "Finnish degree expressions" },
      { id: "s6-15", topic: "cultural note: Finns discuss weather as genuine communication, not filler", grammarPoint: "cultural weather context" },
      { id: "s6-16", topic: "Yöpakkanen — nighttime frost (common Finnish concept)", grammarPoint: "compound weather words" },
      { id: "s6-17", topic: "Kaamos — polar night period in northern Finland", grammarPoint: "unique Finnish weather vocabulary" },
      { id: "s6-18", topic: "Miten sää on Suomessa heinäkuussa? — What's the weather in Finland in July?", grammarPoint: "travel-relevant weather question" },
      { id: "s6-19", topic: "Ota takki mukaan — Take a jacket with you", grammarPoint: "imperative + mukaan" },
      { id: "s6-20", topic: "odd one out: talvi / kesä / sää / kevät / syksy", grammarPoint: "season vs general weather", preferredType: "odd_one_out" },
      { id: "s6-21", topic: "Ulkona on kaunis — It is beautiful outside", grammarPoint: "ulkona + on + adjective" },
      { id: "s6-22", topic: "Sataako? — Is it raining?", grammarPoint: "question form of sataa" },
      { id: "s6-23", topic: "Ei sada — It is not raining", grammarPoint: "negation of impersonal verb" },
      { id: "s6-24", topic: "Aurinko ei paista — The sun is not shining", grammarPoint: "negation with ei" },
      { id: "s6-25", topic: "conversation: small talk about weather with Oskari's parents", grammarPoint: "weather small talk", preferredType: "conversation" },
      { id: "s6-26", topic: "Eilen satoi — Yesterday it rained (past tense)", grammarPoint: "impersonal past tense" },
      { id: "s6-27", topic: "Huomenna tulee olemaan aurinkoista — Tomorrow it will be sunny", grammarPoint: "future tulla + olemaan" },
      { id: "s6-28", topic: "fix the mistake: wrong case after sataa", grammarPoint: "partitive after sataa", preferredType: "fix_the_mistake" },
      { id: "s6-29", topic: "Kesäyö on valoisa — Summer night is bright (midnight sun)", grammarPoint: "midsummer vocabulary" },
    ],
  },
  {
    id: "s7",
    name: "Feelings & Reactions",
    finnishName: "Tunteet",
    track: "A",
    order: 7,
    unlockAfter: ["s1"],
    isLeahSkill: false,
    description: "Express how you feel and react warmly as a guest",
    seeds: [
      { id: "s7-0", topic: "Olen väsynyt — I am tired", grammarPoint: "olen + adjective" },
      { id: "s7-1", topic: "Olen iloinen — I am happy", grammarPoint: "olen + adjective", preferredType: "production" },
      { id: "s7-2", topic: "Olen nälkäinen — I am hungry", grammarPoint: "olen + adjective" },
      { id: "s7-3", topic: "Olen janoinen — I am thirsty", grammarPoint: "olen + adjective" },
      { id: "s7-4", topic: "Olen kipeä — I am sick / not feeling well", grammarPoint: "olen + adjective" },
      { id: "s7-5", topic: "Olen innoissani — I am excited", grammarPoint: "inessive plural adjective" },
      { id: "s7-6", topic: "Vau! — Wow! as a reaction", grammarPoint: "exclamations" },
      { id: "s7-7", topic: "Todella? — Really? as a reaction", grammarPoint: "exclamations" },
      { id: "s7-8", topic: "Kuinka hieno! — How wonderful!", grammarPoint: "kuinka + adjective exclamation" },
      { id: "s7-9", topic: "Rakastan tätä — I love this", grammarPoint: "rakastaa + partitive" },
      { id: "s7-10", topic: "Tämä on mahtavaa — This is amazing", grammarPoint: "partitive predicate" },
      { id: "s7-11", topic: "Olen niin onnellinen täällä — I am so happy here", grammarPoint: "olen + niin + adjective" },
      { id: "s7-12", topic: "being a gracious guest: Teillä on niin kodikas koti — Your home is so cozy", grammarPoint: "complimenting home", preferredType: "production" },
      { id: "s7-13", topic: "Tunnen oloni kotoisaksi — I feel at home", grammarPoint: "tuntea olonsa idiomatic" },
      { id: "s7-14", topic: "Arvostan teidän vieraanvaraisuuttanne — I appreciate your hospitality", grammarPoint: "arvostaa + partitive" },
      { id: "s7-15", topic: "Minulla on hauskaa — I am having fun", grammarPoint: "minulla on hauskaa expression" },
      { id: "s7-16", topic: "Pidän siitä — I like it/that", grammarPoint: "pitää + elative" },
      { id: "s7-17", topic: "En pidä siitä — I don't like it", grammarPoint: "negation of pitää" },
      { id: "s7-18", topic: "Olen surullinen — I am sad", grammarPoint: "sad feelings" },
      { id: "s7-19", topic: "Olen hermostunut — I am nervous", grammarPoint: "nervous feelings" },
      { id: "s7-20", topic: "Onko sinulla hyvä olo? — Are you feeling well?", grammarPoint: "olo expression" },
      { id: "s7-21", topic: "Minulla on hyvä olo — I feel good", grammarPoint: "olo expression" },
      { id: "s7-22", topic: "Kiitos kaiken kukkuraksi — Thank you for everything (gratitude at end of visit)", grammarPoint: "gratitude expressions" },
      { id: "s7-23", topic: "Tämä on paras matka! — This is the best trip!", grammarPoint: "superlative paras" },
      { id: "s7-24", topic: "odd one out: iloinen / väsynyt / nälkäinen / talo", grammarPoint: "emotions vs things", preferredType: "odd_one_out" },
      { id: "s7-25", topic: "Se oli upea kokemus — It was a wonderful experience", grammarPoint: "past tense + adjective" },
      { id: "s7-26", topic: "fix the mistake: olen nälkäistä (wrong case on adjective)", grammarPoint: "predicate adjective case", preferredType: "fix_the_mistake" },
      { id: "s7-27", topic: "Tunteet sanoin — putting feelings into words, describing your emotional state", grammarPoint: "emotional vocabulary production", preferredType: "production" },
      { id: "s7-28", topic: "conversation: arriving at Oskari's family home and expressing excitement", grammarPoint: "guest arrival dialogue", preferredType: "conversation" },
      { id: "s7-29", topic: "Olen todella kiitollinen — I am truly grateful", grammarPoint: "kiitollinen + todella", preferredType: "production" },
    ],
  },
  {
    id: "s8",
    name: "Questions & Answers",
    finnishName: "Kysymykset",
    track: "A",
    order: 8,
    unlockAfter: ["s1"],
    isLeahSkill: false,
    description: "Question words and asking for help understanding",
    seeds: [
      { id: "s8-0", topic: "Mikä — what (for things)", grammarPoint: "question word mikä" },
      { id: "s8-1", topic: "Kuka — who", grammarPoint: "question word kuka" },
      { id: "s8-2", topic: "Missä — where (location, inessive)", grammarPoint: "question word missä" },
      { id: "s8-3", topic: "Milloin — when", grammarPoint: "question word milloin" },
      { id: "s8-4", topic: "Miksi — why", grammarPoint: "question word miksi" },
      { id: "s8-5", topic: "Miten / Kuinka — how", grammarPoint: "question words miten and kuinka" },
      { id: "s8-6", topic: "Kuinka paljon — how much", grammarPoint: "quantity question" },
      { id: "s8-7", topic: "En ymmärrä — I don't understand", grammarPoint: "negation of ymmärtää", preferredType: "production" },
      { id: "s8-8", topic: "Voitko toistaa? — Can you repeat that?", grammarPoint: "voitko + infinitive", preferredType: "production" },
      { id: "s8-9", topic: "Voitko puhua hitaammin? — Can you speak more slowly?", grammarPoint: "voitko + comparative adverb", preferredType: "production" },
      { id: "s8-10", topic: "Mitä tämä tarkoittaa? — What does this mean?", grammarPoint: "tarkoittaa verb" },
      { id: "s8-11", topic: "Miten sanotaan X suomeksi? — How do you say X in Finnish?", grammarPoint: "sanotaan passive", preferredType: "production" },
      { id: "s8-12", topic: "Anteeksi, missä on WC? — Excuse me, where is the toilet?", grammarPoint: "location question practical" },
      { id: "s8-13", topic: "Kuka tämä on? — Who is this?", grammarPoint: "kuka question" },
      { id: "s8-14", topic: "Milloin lähdette? — When are you leaving?", grammarPoint: "milloin + lähteä" },
      { id: "s8-15", topic: "Miksi suomi on niin vaikea? — Why is Finnish so hard?", grammarPoint: "miksi question" },
      { id: "s8-16", topic: "Kuinka kauan — how long (duration)", grammarPoint: "duration question" },
      { id: "s8-17", topic: "Kuinka monta — how many", grammarPoint: "quantity question" },
      { id: "s8-18", topic: "Mistä — from where", grammarPoint: "elative question" },
      { id: "s8-19", topic: "Mihin — to where", grammarPoint: "illative question" },
      { id: "s8-20", topic: "forming yes/no questions with -ko/-kö suffix", grammarPoint: "interrogative suffix" },
      { id: "s8-21", topic: "Onko — is there / is it (question form of on)", grammarPoint: "onko question" },
      { id: "s8-22", topic: "Haluatko — do you want (question form)", grammarPoint: "haluatko question" },
      { id: "s8-23", topic: "odd one out: mikä / kuka / missä / suomi / milloin", grammarPoint: "question words vs nouns", preferredType: "odd_one_out" },
      { id: "s8-24", topic: "Puhutko englantia? — Do you speak English?", grammarPoint: "practical backup question" },
      { id: "s8-25", topic: "Ymmärrätkö suomea? — Do you understand Finnish?", grammarPoint: "comprehension question" },
      { id: "s8-26", topic: "Mitä kuuluu? — How are things? (lit. what is heard)", grammarPoint: "common question idiom" },
      { id: "s8-27", topic: "fix the mistake: Missä sinä menet? (should be Mihin)", grammarPoint: "missä vs mihin distinction", preferredType: "fix_the_mistake" },
      { id: "s8-28", topic: "conversation: not understanding and asking for clarification", grammarPoint: "clarification dialogue", preferredType: "conversation" },
      { id: "s8-29", topic: "Kerrotko lisää? — Could you tell me more?", grammarPoint: "conditional request" },
    ],
  },
  {
    id: "s9",
    name: "Numbers, Time & Dates",
    finnishName: "Numerot ja aika",
    track: "A",
    order: 9,
    unlockAfter: ["s1"],
    isLeahSkill: false,
    description: "1–100, clock time, days, months, making plans",
    seeds: [
      { id: "s9-0", topic: "numbers 1–10: yksi, kaksi, kolme, neljä, viisi, kuusi, seitsemän, kahdeksan, yhdeksän, kymmenen", grammarPoint: "cardinal numbers 1-10" },
      { id: "s9-1", topic: "numbers 11–20: yksitoista through kaksikymmentä", grammarPoint: "teen numbers" },
      { id: "s9-2", topic: "tens: kaksikymmentä, kolmekymmentä... sata", grammarPoint: "tens and hundred" },
      { id: "s9-3", topic: "compound numbers: kaksikymmentäviisi (25), kolmekymmentäkahdeksan (38)", grammarPoint: "compound numbers" },
      { id: "s9-4", topic: "ordinals: ensimmäinen, toinen, kolmas, neljäs, viides", grammarPoint: "ordinal numbers 1-5" },
      { id: "s9-5", topic: "ordinals: kuudes through kymmenes", grammarPoint: "ordinal numbers 6-10" },
      { id: "s9-6", topic: "Kello on kolme — It is three o'clock", grammarPoint: "clock time expression" },
      { id: "s9-7", topic: "Kello on puoli neljä — It is half past three (lit. half four)", grammarPoint: "half hours in Finnish (puoli = half of next hour)" },
      { id: "s9-8", topic: "Kello on varttia vaille viisi — It is quarter to five", grammarPoint: "quarter hour expressions" },
      { id: "s9-9", topic: "Tavataan kello kolme — Let's meet at three o'clock", grammarPoint: "making plans with time", preferredType: "production" },
      { id: "s9-10", topic: "Huomenna — tomorrow, eilen — yesterday, tänään — today", grammarPoint: "basic time adverbs" },
      { id: "s9-11", topic: "Ensi viikolla — next week, viime viikolla — last week", grammarPoint: "week time expressions" },
      { id: "s9-12", topic: "days of week: maanantai, tiistai, keskiviikko, torstai, perjantai, lauantai, sunnuntai", grammarPoint: "days of the week" },
      { id: "s9-13", topic: "months: tammikuu through joulukuu", grammarPoint: "months of the year" },
      { id: "s9-14", topic: "Heinäkuun kahdeskymmenesviides — July 25th (Leah's trip date)", grammarPoint: "date expression ordinal" },
      { id: "s9-15", topic: "Syntymäpäiväni on... — My birthday is on...", grammarPoint: "birthday date" },
      { id: "s9-16", topic: "Mihin aikaan? — At what time?", grammarPoint: "time question" },
      { id: "s9-17", topic: "Kello kahden aikaan — Around two o'clock", grammarPoint: "approximate time" },
      { id: "s9-18", topic: "Iltapäivällä / aamulla / illalla — in the afternoon / morning / evening", grammarPoint: "time of day adessives" },
      { id: "s9-19", topic: "puolen päivän aikaan — around noon", grammarPoint: "midday expression" },
      { id: "s9-20", topic: "odd one out: maanantai / tiistai / heinäkuu / torstai", grammarPoint: "days vs months", preferredType: "odd_one_out" },
      { id: "s9-21", topic: "Kuinka monta päivää on viikossa? — How many days are in a week?", grammarPoint: "number question" },
      { id: "s9-22", topic: "Monesko päivä tänään on? — What day of the month is today?", grammarPoint: "date question" },
      { id: "s9-23", topic: "Minulla on aika X — I have an appointment at X", grammarPoint: "scheduling vocabulary" },
      { id: "s9-24", topic: "Tavataan huomenna — Let's meet tomorrow", grammarPoint: "making plans", preferredType: "production" },
      { id: "s9-25", topic: "fix the mistake: Kello on kolme ja puoli (should be puoli neljä)", grammarPoint: "Finnish half hour", preferredType: "fix_the_mistake" },
      { id: "s9-26", topic: "Moneltako? — At what time? (colloquial)", grammarPoint: "colloquial time question" },
      { id: "s9-27", topic: "Kolmelta — at three (ablative time)", grammarPoint: "ablative for times" },
      { id: "s9-28", topic: "conversation: arranging to meet Oskari's family member at a specific time", grammarPoint: "planning dialogue", preferredType: "conversation" },
      { id: "s9-29", topic: "Kuukauden päästä — in a month's time", grammarPoint: "päästä for future duration" },
    ],
  },
  {
    id: "s10",
    name: "Travel & Directions",
    finnishName: "Matkailu",
    track: "A",
    order: 10,
    unlockAfter: ["s8", "s9"],
    isLeahSkill: false,
    description: "Getting around Helsinki and small-town Finland",
    seeds: [
      { id: "s10-0", topic: "vasemmalle — to the left", grammarPoint: "allative directions" },
      { id: "s10-1", topic: "oikealle — to the right", grammarPoint: "allative directions" },
      { id: "s10-2", topic: "suoraan — straight ahead", grammarPoint: "direction adverb" },
      { id: "s10-3", topic: "bussi — bus, juna — train, taksi — taxi, lentokone — airplane", grammarPoint: "transport vocabulary" },
      { id: "s10-4", topic: "Missä on bussipysäkki? — Where is the bus stop?", grammarPoint: "location question + transport" },
      { id: "s10-5", topic: "Miten pääsen rautatieasemalle? — How do I get to the train station?", grammarPoint: "päästä verb + illative" },
      { id: "s10-6", topic: "Käännyt vasemmalle ja sitten suoraan — Turn left and then straight", grammarPoint: "giving directions sequence" },
      { id: "s10-7", topic: "Kuinka kaukana se on? — How far is it?", grammarPoint: "distance question" },
      { id: "s10-8", topic: "Se on lähellä — It is nearby, Se on kaukana — It is far", grammarPoint: "proximity adverbs" },
      { id: "s10-9", topic: "Lentokenttä — airport, Helsinki-Vantaa is the main one", grammarPoint: "airport vocabulary" },
      { id: "s10-10", topic: "Lippu — ticket, ostaa lippu — to buy a ticket", grammarPoint: "ticket vocabulary" },
      { id: "s10-11", topic: "Menolippu / menopaluulippu — one-way / return ticket", grammarPoint: "ticket types" },
      { id: "s10-12", topic: "Milloin juna lähtee? — When does the train leave?", grammarPoint: "departure question" },
      { id: "s10-13", topic: "Rautatieasema — train station, metro — metro", grammarPoint: "transport hub vocabulary" },
      { id: "s10-14", topic: "Anteeksi, eksyin — Excuse me, I am lost", grammarPoint: "getting lost expression" },
      { id: "s10-15", topic: "Voitko näyttää kartalla? — Can you show me on the map?", grammarPoint: "asking for map help" },
      { id: "s10-16", topic: "Olen menossa Helsinkiin — I am going to Helsinki", grammarPoint: "olla menossa + illative" },
      { id: "s10-17", topic: "Tulen Tampereelta — I am coming from Tampere", grammarPoint: "elative for departure point" },
      { id: "s10-18", topic: "Kaupunki — city, kylä — village, maaseutu — countryside", grammarPoint: "settlement types" },
      { id: "s10-19", topic: "Kadun nimi — street name, osoite — address", grammarPoint: "address vocabulary" },
      { id: "s10-20", topic: "Onko tässä lähellä kauppa? — Is there a shop nearby?", grammarPoint: "local navigation" },
      { id: "s10-21", topic: "Kauanko matka kestää? — How long does the journey take?", grammarPoint: "journey duration" },
      { id: "s10-22", topic: "odd one out: bussi / juna / taksi / kylä / lentokone", grammarPoint: "transport vs place", preferredType: "odd_one_out" },
      { id: "s10-23", topic: "Menen kotiin — I'm going home", grammarPoint: "illative koti" },
      { id: "s10-24", topic: "Tule sisään — Come in (when arriving at someone's home)", grammarPoint: "imperative welcome phrase" },
      { id: "s10-25", topic: "fix the mistake: wrong postposition for direction", grammarPoint: "allative vs adessive for direction", preferredType: "fix_the_mistake" },
      { id: "s10-26", topic: "HSL — Helsinki transport system, reitti — route", grammarPoint: "Helsinki public transport" },
      { id: "s10-27", topic: "Paikallinen — local, as in local bus vs long-distance", grammarPoint: "transport type distinction" },
      { id: "s10-28", topic: "conversation: asking for directions in a small Finnish town", grammarPoint: "directions dialogue", preferredType: "conversation" },
      { id: "s10-29", topic: "Tervetuloa Suomeen! — Welcome to Finland!", grammarPoint: "arrival expression", preferredType: "production" },
    ],
  },
  // Track B
  {
    id: "s11",
    name: "Verb Types 1–3",
    finnishName: "Verbitypit",
    track: "B",
    order: 11,
    unlockAfter: ["s1"],
    isLeahSkill: false,
    description: "The three main conjugation patterns — with verbs you already know",
    seeds: [
      { id: "s11-0", topic: "Type 1 verbs: stem ends in vowel, add -n for minä. puhua → puhun", grammarPoint: "type 1 conjugation" },
      { id: "s11-1", topic: "Type 1: asua → asun, I live", grammarPoint: "type 1 familiar verb" },
      { id: "s11-2", topic: "Type 1: juoda → juon (vowel contraction oa→o)", grammarPoint: "type 1 vowel contraction" },
      { id: "s11-3", topic: "Type 1: all persons: puhun, puhut, puhuu, puhumme, puhutte, puhuvat", grammarPoint: "type 1 full paradigm" },
      { id: "s11-4", topic: "Type 2 verbs: infinitive ends in -da/-dä. syödä → syön", grammarPoint: "type 2 conjugation" },
      { id: "s11-5", topic: "Type 2: juoda → juon, saada → saan", grammarPoint: "type 2 familiar verbs" },
      { id: "s11-6", topic: "Type 2: full paradigm — syön, syöt, syö, syömme, syötte, syövät", grammarPoint: "type 2 full paradigm" },
      { id: "s11-7", topic: "Type 3 verbs: infinitive ends in -la/-lä/-na/-na/-ra/-sta. tulla → tulen", grammarPoint: "type 3 conjugation" },
      { id: "s11-8", topic: "Type 3: mennä → menen, olla → olen", grammarPoint: "type 3 familiar verbs" },
      { id: "s11-9", topic: "Type 3: full paradigm — tulen, tulet, tulee, tulemme, tulette, tulevat", grammarPoint: "type 3 full paradigm" },
      { id: "s11-10", topic: "identifying verb type from infinitive ending", grammarPoint: "verb type identification" },
      { id: "s11-11", topic: "lukea (type 1 or 2?) — type 2: luen, luet, lukee", grammarPoint: "lukea conjugation" },
      { id: "s11-12", topic: "neuloa — type 1: neulon, neulot, neuloo", grammarPoint: "neuloa conjugation (Leah's verb)" },
      { id: "s11-13", topic: "tehdä — type 2: teen, teet, tekee (irregular stem)", grammarPoint: "tehdä irregular type 2" },
      { id: "s11-14", topic: "conjugating tykkään: pitää/tykätä — type 4 preview", grammarPoint: "tykätä conjugation" },
      { id: "s11-15", topic: "fix the mistake: puhu instead of puhun for minä", grammarPoint: "personal ending", preferredType: "fix_the_mistake" },
      { id: "s11-16", topic: "odd one out: puhua / asua / syödä / juoda (type 1,1,2,2)", grammarPoint: "sorting by verb type", preferredType: "odd_one_out" },
      { id: "s11-17", topic: "osata — type 4: osaan, osaat, osaa", grammarPoint: "osata (I know how to) conjugation" },
      { id: "s11-18", topic: "haluta — type 4: haluan, haluat, haluaa", grammarPoint: "haluta conjugation" },
      { id: "s11-19", topic: "ymmärtää — type 1 long vowel: ymmärrän", grammarPoint: "ymmärtää double consonant" },
      { id: "s11-20", topic: "kuulla — type 2: kuulen, hear", grammarPoint: "kuulla conjugation" },
      { id: "s11-21", topic: "nähdä — type 2: näen, see", grammarPoint: "nähdä conjugation" },
      { id: "s11-22", topic: "tietää — type 1: tiedän, know (fact)", grammarPoint: "tietää conjugation" },
      { id: "s11-23", topic: "vowel harmony: back vowels (a,o,u) vs front vowels (ä,ö,y)", grammarPoint: "vowel harmony rule" },
      { id: "s11-24", topic: "applying vowel harmony to verb endings: -an vs -än", grammarPoint: "vowel harmony in conjugation" },
      { id: "s11-25", topic: "consonant gradation preview: puhun → puhua (k→∅, p→v, t→d)", grammarPoint: "consonant gradation basics" },
      { id: "s11-26", topic: "conversation: identifying verb types in a short text about Leah's day", grammarPoint: "verb recognition in context", preferredType: "conversation" },
      { id: "s11-27", topic: "production: conjugate juosta (to run) for all persons", grammarPoint: "full paradigm production", preferredType: "production" },
      { id: "s11-28", topic: "case_ending: add correct ending to make puhun from puhu-", grammarPoint: "personal ending fill-in", preferredType: "case_ending" },
      { id: "s11-29", topic: "case_ending: add correct ending for sinä form of asua", grammarPoint: "second person singular", preferredType: "case_ending" },
    ],
  },
  {
    id: "s12",
    name: "Nominative & Genitive",
    finnishName: "Nominatiivi ja genetiivi",
    track: "B",
    order: 12,
    unlockAfter: ["s11"],
    isLeahSkill: false,
    description: "Subject case and possession — Oskarin perhe, kissan nimi",
    seeds: [
      { id: "s12-0", topic: "nominative: the base form, used as subject", grammarPoint: "nominative function" },
      { id: "s12-1", topic: "genitive: adds -n to stem, shows possession", grammarPoint: "genitive formation" },
      { id: "s12-2", topic: "Oskarin perhe — Oskari's family (genitive)", grammarPoint: "genitive possession", preferredType: "production" },
      { id: "s12-3", topic: "kissan nimi — the cat's name (genitive)", grammarPoint: "genitive possession", preferredType: "production" },
      { id: "s12-4", topic: "Suomen kieli — the Finnish language (genitive)", grammarPoint: "genitive in compound-like phrases" },
      { id: "s12-5", topic: "Leahn koti — Leah's home (genitive of foreign name)", grammarPoint: "genitive of proper nouns" },
      { id: "s12-6", topic: "genitive after postpositions: Oskarin kanssa — with Oskari", grammarPoint: "genitive + kanssa" },
      { id: "s12-7", topic: "genitive after postpositions: talon edessä — in front of the house", grammarPoint: "genitive + edessä" },
      { id: "s12-8", topic: "genitive: puiston vieressä — next to the park", grammarPoint: "genitive + vieressä" },
      { id: "s12-9", topic: "long vowel shortens before -n: maa → maan, puu → puun", grammarPoint: "genitive of long-vowel words" },
      { id: "s12-10", topic: "consonant gradation in genitive: tyttö → tytön", grammarPoint: "genitive consonant gradation" },
      { id: "s12-11", topic: "isoäidin huone — grandmother's room", grammarPoint: "genitive in family context" },
      { id: "s12-12", topic: "nominative plural vs genitive singular: kissat (cats) vs kissan (cat's)", grammarPoint: "nominative plural vs genitive singular" },
      { id: "s12-13", topic: "case_ending: Kiki___ nimi (Kiki's name)", grammarPoint: "genitive ending", preferredType: "case_ending" },
      { id: "s12-14", topic: "case_ending: Suomi___ talvi (Finland's winter)", grammarPoint: "genitive of Suomi (Suomen)", preferredType: "case_ending" },
      { id: "s12-15", topic: "production: write three possessive phrases about family/pets", grammarPoint: "genitive production", preferredType: "production" },
      { id: "s12-16", topic: "nominative as predicate: Kissa on musta — The cat is black", grammarPoint: "predicate nominative" },
      { id: "s12-17", topic: "fix the mistake: Oskariin perhe (wrong case)", grammarPoint: "genitive not illative for possession", preferredType: "fix_the_mistake" },
      { id: "s12-18", topic: "kaupungin keskusta — city center (genitive)", grammarPoint: "genitive in compound nouns" },
      { id: "s12-19", topic: "ihmisen täytyy — a person must (genitive as subject of täytyy)", grammarPoint: "genitive subject with necessity" },
      { id: "s12-20", topic: "Suomen kesä on kaunis — Finland's summer is beautiful", grammarPoint: "genitive + noun phrase" },
      { id: "s12-21", topic: "odd one out: kissan / Oskarin / talvi / isoäidin (nominative hides)", grammarPoint: "identifying cases", preferredType: "odd_one_out" },
      { id: "s12-22", topic: "genitive after numerals: kaksi kissaa — not genitive but partitive (preview)", grammarPoint: "genitive vs partitive after numbers" },
      { id: "s12-23", topic: "kotini — my home: possessive suffix vs minun koti", grammarPoint: "possessive suffixes preview" },
      { id: "s12-24", topic: "linnan linna — the castle of the fortress, genitive chains", grammarPoint: "genitive chains" },
      { id: "s12-25", topic: "Pojan nimi on Mikko — The boy's name is Mikko", grammarPoint: "genitive in sentence" },
      { id: "s12-26", topic: "conversation: describing whose things are whose at family home", grammarPoint: "genitive in context", preferredType: "conversation" },
      { id: "s12-27", topic: "case_ending: Leah___ työ (Leah's job)", grammarPoint: "genitive of proper name ending in vowel", preferredType: "case_ending" },
      { id: "s12-28", topic: "vuoden alussa — at the start of the year (genitive + postposition)", grammarPoint: "time expressions with genitive" },
      { id: "s12-29", topic: "production: Oskarin perheen isoäiti asuu maalla", grammarPoint: "chained genitive production", preferredType: "production" },
    ],
  },
  {
    id: "s13",
    name: "Partitive Case",
    finnishName: "Partitiivi",
    track: "B",
    order: 13,
    unlockAfter: ["s12"],
    isLeahSkill: false,
    description: "The most important and hardest case — indefinite quantities, negation, after numbers",
    seeds: [
      { id: "s13-0", topic: "partitive signals indefinite/uncountable amount: Juon kahvia — I drink coffee", grammarPoint: "partitive for uncountable" },
      { id: "s13-1", topic: "kaksi kissaa — two cats (partitive after numbers 2+)", grammarPoint: "partitive after numbers", preferredType: "production" },
      { id: "s13-2", topic: "partitive after negation: En syö lihaa — I don't eat meat", grammarPoint: "partitive in negation", preferredType: "production" },
      { id: "s13-3", topic: "forming partitive: kissa → kissaa, koira → koiraa (add -a/-ä)", grammarPoint: "partitive formation vowel-final" },
      { id: "s13-4", topic: "forming partitive: consonant-final: lintu → lintua", grammarPoint: "partitive formation consonant-final" },
      { id: "s13-5", topic: "vettä — water (partitive), maitoa — milk (partitive)", grammarPoint: "partitive of common drinks" },
      { id: "s13-6", topic: "partitive with quantity words: paljon, vähän, hieman + partitive", grammarPoint: "quantity words + partitive" },
      { id: "s13-7", topic: "Puhun suomea — I speak Finnish (ongoing, partitive object)", grammarPoint: "ongoing action partitive object" },
      { id: "s13-8", topic: "nominative vs partitive object: completed vs ongoing", grammarPoint: "object case distinction" },
      { id: "s13-9", topic: "Ostan kirjan — I buy THE book (nominative, complete) vs kirjaa (partitive, ongoing)", grammarPoint: "totality vs partiality" },
      { id: "s13-10", topic: "case_ending: Haluan kahv___ (partitive)", grammarPoint: "partitive fill-in", preferredType: "case_ending" },
      { id: "s13-11", topic: "case_ending: Meillä on kaksi kiss___ (partitive)", grammarPoint: "partitive after kaksi", preferredType: "case_ending" },
      { id: "s13-12", topic: "case_ending: En ymmärrä suome___ (partitive)", grammarPoint: "partitive after negation", preferredType: "case_ending" },
      { id: "s13-13", topic: "partitive of adjectives must agree: hyvää kahvia — good coffee", grammarPoint: "adjective-noun partitive agreement" },
      { id: "s13-14", topic: "herkullista ruokaa — delicious food (partitive adjective + noun)", grammarPoint: "partitive adjective agreement" },
      { id: "s13-15", topic: "predicate adjective in partitive: Kahvi on kuumaa — Coffee is hot", grammarPoint: "predicate partitive" },
      { id: "s13-16", topic: "fix the mistake: Minulla on kaksi kissa (missing partitive)", grammarPoint: "partitive after numbers", preferredType: "fix_the_mistake" },
      { id: "s13-17", topic: "fix the mistake: En syö liha (missing partitive after negation)", grammarPoint: "partitive in negation", preferredType: "fix_the_mistake" },
      { id: "s13-18", topic: "verbs that always take partitive object: rakastaa, odottaa, kuunnella", grammarPoint: "verbs requiring partitive" },
      { id: "s13-19", topic: "Rakastan suomea — I love Finnish (partitive with rakastaa)", grammarPoint: "rakastaa + partitive" },
      { id: "s13-20", topic: "Odotan junaa — I am waiting for the train (partitive with odottaa)", grammarPoint: "odottaa + partitive" },
      { id: "s13-21", topic: "Kuuntelen musiikkia — I listen to music (partitive with kuunnella)", grammarPoint: "kuunnella + partitive" },
      { id: "s13-22", topic: "odd one out: kissaa / kahvia / juoda / koiraa (verb hides)", grammarPoint: "partitive nouns vs verb", preferredType: "odd_one_out" },
      { id: "s13-23", topic: "production: write what you eat and drink using partitive", grammarPoint: "partitive in food context", preferredType: "production" },
      { id: "s13-24", topic: "Jonkin verran suomea — Some Finnish (partitive in degree expressions)", grammarPoint: "jonkin verran + partitive" },
      { id: "s13-25", topic: "paljonko vs kuinka paljon — asking quantity questions", grammarPoint: "quantity questions" },
      { id: "s13-26", topic: "conversation: ordering food with partitive", grammarPoint: "partitive in restaurant", preferredType: "conversation" },
      { id: "s13-27", topic: "partitive of pronouns: minua, sinua, häntä — me, you, him/her", grammarPoint: "partitive pronouns" },
      { id: "s13-28", topic: "Hän rakastaa minua — He loves me (pronoun partitive)", grammarPoint: "pronoun as partitive object" },
      { id: "s13-29", topic: "production: Kaksi kissaa, vähän kahvia, paljon rakkautta — using three partitives", grammarPoint: "multiple partitives", preferredType: "production" },
    ],
  },
  {
    id: "s14",
    name: "Locative Cases",
    finnishName: "Paikallissijat",
    track: "B",
    order: 14,
    unlockAfter: ["s12"],
    isLeahSkill: false,
    description: "missä/mistä/mihin — the six locative cases for where/from/to",
    seeds: [
      { id: "s14-0", topic: "internal: -ssa/-ssä (inessive, missä) = inside something", grammarPoint: "inessive case" },
      { id: "s14-1", topic: "internal: -sta/-stä (elative, mistä) = out of something", grammarPoint: "elative case" },
      { id: "s14-2", topic: "internal: -an/-ään (illative, mihin) = into something", grammarPoint: "illative case" },
      { id: "s14-3", topic: "external: -lla/-llä (adessive, missä) = on/at surface", grammarPoint: "adessive case" },
      { id: "s14-4", topic: "external: -lta/-ltä (ablative, mistä) = from surface", grammarPoint: "ablative case" },
      { id: "s14-5", topic: "external: -lle (allative, mihin) = onto surface", grammarPoint: "allative case" },
      { id: "s14-6", topic: "Asun Helsingissä — I live in Helsinki (inessive)", grammarPoint: "inessive for city location" },
      { id: "s14-7", topic: "Tulen Helsingistä — I come from Helsinki (elative)", grammarPoint: "elative for city origin" },
      { id: "s14-8", topic: "Menen Helsinkiin — I'm going to Helsinki (illative)", grammarPoint: "illative for city destination" },
      { id: "s14-9", topic: "Asun Culver Cityssä — (inessive for foreign place name)", grammarPoint: "inessive of foreign names" },
      { id: "s14-10", topic: "pöydällä — on the table (adessive for surface)", grammarPoint: "adessive for surfaces" },
      { id: "s14-11", topic: "pöydältä — from the table (ablative)", grammarPoint: "ablative from surface" },
      { id: "s14-12", topic: "pöydälle — onto the table (allative)", grammarPoint: "allative to surface" },
      { id: "s14-13", topic: "kotona (at home, adessive), kotoa (from home, ablative), kotiin (to home, illative special)", grammarPoint: "koti locative forms" },
      { id: "s14-14", topic: "Olen kotona — I am at home (adessive)", grammarPoint: "adessive for being at home" },
      { id: "s14-15", topic: "Tulen kotoa — I am coming from home (ablative)", grammarPoint: "ablative from home" },
      { id: "s14-16", topic: "Menen kotiin — I am going home (illative special)", grammarPoint: "kotiin special form" },
      { id: "s14-17", topic: "tykkään Suomesta — I like Finland (elative after tykkään)", grammarPoint: "elative with tykkään" },
      { id: "s14-18", topic: "case_ending: Olen kaupungi___ (inessive)", grammarPoint: "inessive fill-in", preferredType: "case_ending" },
      { id: "s14-19", topic: "case_ending: Tulen kaupungi___ (elative)", grammarPoint: "elative fill-in", preferredType: "case_ending" },
      { id: "s14-20", topic: "case_ending: Menen kaupunki___ (illative)", grammarPoint: "illative fill-in", preferredType: "case_ending" },
      { id: "s14-21", topic: "internal vs external: table uses external (pöydällä), box uses internal (laatikossa)", grammarPoint: "choosing internal vs external cases" },
      { id: "s14-22", topic: "fix the mistake: Menen Helsinkissä (should be Helsinkiin)", grammarPoint: "illative not inessive for destination", preferredType: "fix_the_mistake" },
      { id: "s14-23", topic: "fix the mistake: Tulen Helsinkiin (should be Helsingistä)", grammarPoint: "elative not illative for origin", preferredType: "fix_the_mistake" },
      { id: "s14-24", topic: "odd one out: -ssa / -sta / -lle / -ssa (two inessives?)", grammarPoint: "case ending recognition", preferredType: "odd_one_out" },
      { id: "s14-25", topic: "production: describe where you live using all three internal cases", grammarPoint: "internal case production", preferredType: "production" },
      { id: "s14-26", topic: "Hyllyltä — from the shelf (ablative), hyllylle — onto the shelf (allative)", grammarPoint: "shelf location practice" },
      { id: "s14-27", topic: "conversation: explaining where you've been and where you're going", grammarPoint: "locative cases in context", preferredType: "conversation" },
      { id: "s14-28", topic: "Olen ollut Suomessa ennenkin — I have been in Finland before", grammarPoint: "inessive in perfect tense" },
      { id: "s14-29", topic: "production: Menen isoäidin luokse (to grandmother's place) — luokse postposition", grammarPoint: "luokse vs illative", preferredType: "production" },
    ],
  },
  {
    id: "s15",
    name: "Negation",
    finnishName: "Kieltolause",
    track: "B",
    order: 15,
    unlockAfter: ["s11"],
    isLeahSkill: false,
    description: "ei conjugated + verb stem — En tiedä, hän ei ole, emme ymmärrä",
    seeds: [
      { id: "s15-0", topic: "negation verb ei conjugated: en, et, ei, emme, ette, eivät", grammarPoint: "negation verb paradigm" },
      { id: "s15-1", topic: "en + verb stem (no personal ending): en puhu, not en puhun", grammarPoint: "verb stem in negation" },
      { id: "s15-2", topic: "En tiedä — I don't know", grammarPoint: "en + tiedä", preferredType: "production" },
      { id: "s15-3", topic: "En ymmärrä — I don't understand", grammarPoint: "en + ymmärrä", preferredType: "production" },
      { id: "s15-4", topic: "Hän ei ole kotona — He/she is not home", grammarPoint: "ei + ole (olla negation)" },
      { id: "s15-5", topic: "Emme ymmärrä — We don't understand", grammarPoint: "emme + verb stem" },
      { id: "s15-6", topic: "Et puhu suomea? — You don't speak Finnish?", grammarPoint: "et + verb stem" },
      { id: "s15-7", topic: "Eivät tiedä — They don't know", grammarPoint: "eivät + verb stem" },
      { id: "s15-8", topic: "En syö naudanlihaa — I don't eat beef (partitive in negation)", grammarPoint: "negation + partitive object" },
      { id: "s15-9", topic: "En pidä siitä — I don't like it (negation of pitää)", grammarPoint: "negation of pitää" },
      { id: "s15-10", topic: "Ei ole — there isn't / he/she isn't (ei + ole)", grammarPoint: "ei ole expression" },
      { id: "s15-11", topic: "Ei mitään — it's nothing / never mind", grammarPoint: "ei mitään idiom" },
      { id: "s15-12", topic: "Ei kai — surely not / I don't think so", grammarPoint: "modal particles with negation" },
      { id: "s15-13", topic: "En voi — I can't (en + voi from voida)", grammarPoint: "negation of modal voida" },
      { id: "s15-14", topic: "En halua — I don't want (en + halua)", grammarPoint: "negation of haluta" },
      { id: "s15-15", topic: "Ei se haittaa — It doesn't matter", grammarPoint: "ei se haittaa idiom" },
      { id: "s15-16", topic: "case_ending: E___ puhu (she doesn't speak — fill in ei)", grammarPoint: "negation verb form", preferredType: "case_ending" },
      { id: "s15-17", topic: "fix the mistake: En puhun suomea (wrong: verb has personal ending)", grammarPoint: "verb stem not conjugated in negation", preferredType: "fix_the_mistake" },
      { id: "s15-18", topic: "fix the mistake: Hän ei olla kotona (wrong: ei + ole, not infinitive)", grammarPoint: "ei + verb stem rule", preferredType: "fix_the_mistake" },
      { id: "s15-19", topic: "negation of past tense: en puhunut — I didn't speak", grammarPoint: "past tense negation preview" },
      { id: "s15-20", topic: "Ei saa — you must not / it is not allowed", grammarPoint: "ei saa prohibition" },
      { id: "s15-21", topic: "Älä! — Don't! (imperative negation)", grammarPoint: "imperative negation" },
      { id: "s15-22", topic: "Älä huoli — Don't worry", grammarPoint: "älä huoli idiom" },
      { id: "s15-23", topic: "odd one out: en / et / ei / olla / emme (infinitive hides)", grammarPoint: "negation paradigm vs infinitive", preferredType: "odd_one_out" },
      { id: "s15-24", topic: "production: write 3 negative sentences about yourself", grammarPoint: "negation production", preferredType: "production" },
      { id: "s15-25", topic: "En pysty — I'm not able to (pystyä negation)", grammarPoint: "pystyä negation" },
      { id: "s15-26", topic: "Emme me tiedä — We really don't know (emphatic with pronoun)", grammarPoint: "emphatic negation" },
      { id: "s15-27", topic: "conversation: politely declining food/drink at a gathering", grammarPoint: "negation in social context", preferredType: "conversation" },
      { id: "s15-28", topic: "En puhu hyvin suomea mutta yritän — I don't speak Finnish well but I try", grammarPoint: "negation + concession", preferredType: "production" },
      { id: "s15-29", topic: "Ei tule kysymykseen — Out of the question (set phrase with negation)", grammarPoint: "negation idioms" },
    ],
  },
  {
    id: "s16",
    name: "Colloquial Finnish",
    finnishName: "Puhekieli",
    track: "B",
    order: 16,
    unlockAfter: ["s15", "s14"],
    isLeahSkill: false,
    description: "What Oskari's family actually say — spoken vs written Finnish",
    seeds: [
      { id: "s16-0", topic: "minä → mä (spoken first person)", grammarPoint: "spoken pronoun reduction" },
      { id: "s16-1", topic: "sinä → sä (spoken second person)", grammarPoint: "spoken pronoun reduction" },
      { id: "s16-2", topic: "me → me (stays same), te → te (stays same), he → ne (they, colloquial)", grammarPoint: "plural pronoun colloquial" },
      { id: "s16-3", topic: "ei ole → ei oo (contracted spoken form)", grammarPoint: "ei oo contraction" },
      { id: "s16-4", topic: "minulla on → mulla on (spoken possessive)", grammarPoint: "mulla on contraction" },
      { id: "s16-5", topic: "sinulla on → sulla on (spoken possessive)", grammarPoint: "sulla on contraction" },
      { id: "s16-6", topic: "hänellä on → sillä on (spoken he/she has)", grammarPoint: "sillä on contraction" },
      { id: "s16-7", topic: "puhun → mä puhun (spoken adds pronoun explicitly)", grammarPoint: "spoken explicit pronoun" },
      { id: "s16-8", topic: "-inen adjectives: kauniinen → kauniin, iloinen → iloinen (less change)", grammarPoint: "adjective in spoken" },
      { id: "s16-9", topic: "tämä → tää, tuo → toi, se → se (demonstrative reduction)", grammarPoint: "demonstrative reduction" },
      { id: "s16-10", topic: "niin → ni (spoken), sitten → sit (then/then)", grammarPoint: "common adverb reductions" },
      { id: "s16-11", topic: "mikä → mikä (stays), missä → missä (stays) — these don't reduce", grammarPoint: "question words stay the same" },
      { id: "s16-12", topic: "Mulla on nälkä — I'm hungry (spoken vs Minulla on nälkä)", grammarPoint: "spoken hunger expression" },
      { id: "s16-13", topic: "Mä en tiedä — I don't know (spoken vs En tiedä)", grammarPoint: "spoken negation" },
      { id: "s16-14", topic: "Mitä sä teet? — What are you doing? (spoken)", grammarPoint: "spoken question" },
      { id: "s16-15", topic: "Mä oon Leah — I'm Leah (spoken vs Minä olen)", grammarPoint: "spoken olla conjugation" },
      { id: "s16-16", topic: "Hyvää vs hyvää — stays same in speech", grammarPoint: "words unchanged in speech" },
      { id: "s16-17", topic: "fix the mistake: rewrite formal sentence in spoken Finnish", grammarPoint: "formal to spoken conversion", preferredType: "fix_the_mistake" },
      { id: "s16-18", topic: "fix the mistake: identify if text is written or spoken Finnish", grammarPoint: "register identification", preferredType: "fix_the_mistake" },
      { id: "s16-19", topic: "conversation: Oskari's cousin texts you — all in spoken Finnish", grammarPoint: "spoken Finnish in messages", preferredType: "conversation" },
      { id: "s16-20", topic: "Mä tykkään tosta — I like that (spoken elative tuo→toi→tosta)", grammarPoint: "demonstrative elative spoken" },
      { id: "s16-21", topic: "Tuu tänne! — Come here! (spoken imperative vs tule)", grammarPoint: "spoken imperative" },
      { id: "s16-22", topic: "Mä meen kotiin — I'm going home (menen → meen reduction)", grammarPoint: "meen for menen" },
      { id: "s16-23", topic: "Mitä kuuluu? stays same in speech — common phrases unchanged", grammarPoint: "fixed phrases" },
      { id: "s16-24", topic: "odd one out: mä / sä / minä / ne (written form hides)", grammarPoint: "spoken vs written pronouns", preferredType: "odd_one_out" },
      { id: "s16-25", topic: "Ei se mitään — It doesn't matter (spoken vs ei se haittaa)", grammarPoint: "spoken idioms" },
      { id: "s16-26", topic: "production: rewrite Minulla on kaksi kissaa in spoken Finnish", grammarPoint: "written to spoken conversion", preferredType: "production" },
      { id: "s16-27", topic: "production: Mä oon amerikkalainen ja mulla on serkku Suomessa", grammarPoint: "spoken self-description", preferredType: "production" },
      { id: "s16-28", topic: "regional: Tampere area uses 'moro' for hello, some unique vowel sounds", grammarPoint: "regional Finnish dialects" },
      { id: "s16-29", topic: "conversation: understanding rapid spoken Finnish and asking for slower repetition", grammarPoint: "comprehension strategy", preferredType: "conversation" },
    ],
  },
];

export function getSkill(id: string): Skill | undefined {
  return SKILLS.find((s) => s.id === id);
}

export function getUnlockedSkills(completedSkills: string[]): Skill[] {
  return SKILLS.filter((skill) => {
    if (skill.unlockAfter.length === 0) return true;
    return skill.unlockAfter.every((dep) => completedSkills.includes(dep));
  });
}
